### ISSUE TITLE
Poważny błąd

### ISSUE THREAD

**Issue by ProgramistaZpolski** [TheVision6212/TheVision6212#1]
Witam,
jak widzimy w 3 linijce readme, znajduje się katastroficzny błąd.
Jest tam napisane "Python to śmieć za 3zł" podczas gdy python to śmieć za 1zł.
Proszę poprawić ten poważny błąd.
Pozdrawiam.

Also czemu główny branch to "main" a nie "master"

**Comment by TheVision6212** [comment]
przepraszam za taki błąd, już poprawiam

**Comment by TheVision6212** [comment]
Błąd poprawiony
